name: publish-release

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.create_tag.outputs.version }}
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install uv

      - name: Get version
        id: get_version
        run: |
          version=$(python -c "import re; from pathlib import Path; print(re.search(r'__version__\s*=\s*\"([^\"]+)\"', Path('src/prefetch2es/__about__.py').read_text()).group(1))")
          echo "version=$version" >> $GITHUB_ENV
        shell: bash

      - name: run python
        run: |
          uv run prefetch2es -h
          uv run prefetch2es -v
          uv run prefetch2json -h
          uv run prefetch2json -v
      
      - name: build
        run: |
          uv run python -m nuitka --standalone --onefile --follow-imports -o prefetch2es-windows-x64-v$env:version.exe --output-dir=dist --assume-yes-for-downloads src/prefetch2es/views/Prefetch2esView.py
          uv run python -m nuitka --standalone --onefile --follow-imports -o prefetch2json-windows-x64-v$env:version.exe --output-dir=dist --assume-yes-for-downloads src/prefetch2es/views/Prefetch2jsonView.py
      
      - name: verify
        run: |
          dist/prefetch2es-windows-x64-v$version.exe -h
          dist/prefetch2es-windows-x64-v$version.exe -v
          dist/prefetch2json-windows-x64-v$version.exe -h
          dist/prefetch2json-windows-x64-v$version.exe -v
        shell: bash
      
      - name: Create tag
        id: create_tag
        if: startsWith(github.ref, 'refs/heads/master')
        run: |
          git tag "v$version"
          git push origin "v$version"
          echo "version=$version" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.create_tag.outputs.version }}
          files: |
            dist/prefetch2es-windows-x64-v${{ env.version }}.exe
            dist/prefetch2json-windows-x64-v${{ env.version }}.exe
          name: Release v${{ steps.create_tag.outputs.version }}
          body: 'This release was automatically created by GitHub Actions.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    needs: build-windows
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.13']
    env:
      version: ${{ needs.build-windows.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt install patchelf build-essential
          pip install uv

      - name: run python
        run: |
          uv run prefetch2es -h
          uv run prefetch2es -v
          uv run prefetch2json -h
          uv run prefetch2json -v

      - name: build
        run: |
          pip install nuitka
          uv run python -m nuitka --standalone --onefile --follow-imports -o prefetch2es-linux-x64-v$version --output-dir=dist --assume-yes-for-downloads src/prefetch2es/views/Prefetch2esView.py
          uv run python -m nuitka --standalone --onefile --follow-imports -o prefetch2json-linux-x64-v$version --output-dir=dist --assume-yes-for-downloads src/prefetch2es/views/Prefetch2jsonView.py
      
      - name: verify
        run: |
          dist/prefetch2es-linux-x64-v$version -h
          dist/prefetch2es-linux-x64-v$version -v
          dist/prefetch2json-linux-x64-v$version -h
          dist/prefetch2json-linux-x64-v$version -v

      - name: upload asset to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build-windows.outputs.version }}
          files: |
            dist/prefetch2es-linux-x64-v${{ env.version }}
            dist/prefetch2json-linux-x64-v${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
